# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170122_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='future_job',
            field=models.CharField(default='None', max_length=40, verbose_name='future job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='header image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='long_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='short description'),
        ),
    ]
